const areas = [
  { id: 1, name: 'LA PAZ - CENTRO' },
  { id: 2, name: 'LA PAZ - EL ALTO' },
  { id: 3, name: 'LA PAZ- ZONA SUR' },
  { id: 4, name: 'POLICIA RURAL Y FRONTERIZA' },
  { id: 5, name: 'TRANSITO' },
]

const unitsByArea = {
  1: [
    { id: 1101, name: 'E.P.I. COTAHUMA' },
    { id: 1102, name: 'E.P.I.  MUNAYPATA' },
    { id: 1103, name: 'E.P.I.  SAN PEDRO' },
    { id: 1104, name: 'E.P.I.  SAN ANTONIO' },
    { id: 1105, name: 'E.P.I.  FERROVIARIO' },
    { id: 1106, name: 'E.P.I.   LA MERCED' },
    { id: 1107, name: 'E.P.I.  BOSQUESILLO' },
    { id: 1108, name: 'CARABINEROS' },
    { id: 1109, name: 'BATALLÓN DE SEGURIDAD FÍSICA LA PAZ' },
    { id: 1110, name: 'CONCILIACIÓN CIUDADANA Y FAMILIA CENTRO' },
    { id: 1111, name: 'BATALLÓN DE SEGURIDAD FÍSICA ESTATAL' },
    { id: 1112, name: 'U.P.A.R. DELTA CENTRO' },
    { id: 1113, name: 'POLICÍA TURÍSTICA' },
    { id: 1114, name: 'RADIO PATRULLAS 110 - CENTRO' },
    { id: 1115, name: 'P.A.C. CENTRO' },
    { id: 1116, name: 'U.T.O.P. CENTRO' },
    { id: 1117, name: 'GRUPO DE APOYO CIVIL A LA POLICÍA “GACIP"' },
    { id: 1118, name: 'COMANDO DEPARTAMENTAL DE POLICÍA LA PAZ' },
  ],
  2: [
    { id: 2101, name: 'E.P.I. SATELITE' },
    { id: 2102, name: 'E.P.I. HUAYNA POTOSI' },
    { id: 2103, name: 'E.P.I.  ALTO LIMA' },
    { id: 2104, name: 'E.P.I. TARAPACA' },
    { id: 2105, name: 'E.P.I. ALTO CHIJINI' },
    { id: 2106, name: 'E.P.I. VILLA TUNARI' },
    { id: 2107, name: 'UTOP - EL ALTO' },
    { id: 2108, name: 'U.P.A.R. DELTA - EL ALTO' },
    { id: 2109, name: 'GACIP -EL ALTO' },
    { id: 2110, name: 'RADIO PATRULLAS 110 - EL ALTO' },
    { id: 2111, name: 'P.A.C. - EL ALTO' },
    { id: 2112, name: 'UNIDAD DE SEGURIDAD FÍSICA -  EL ALTO' },
    { id: 2113, name: 'CENTRO DE ADIESTRAMIENTO DE CANES - EL ALTO' },
    { id: 2114, name: 'CMDO REGIONAL DE EL ALTO' },
  ],
  3: [
    { id: 3101, name: 'E.P.I. SUR' },
    { id: 3102, name: 'E.P.I. CHASQUIPAMPA' },
    { id: 3103, name: 'UNIDAD DE SEGURIDAD FÍSICA ESTATAL -  ZONA SUR' },
    { id: 3104, name: 'UTOP - ZONA SUR' },
    { id: 3105, name: 'CENTRO DE ADIESTRAMIENTO DE CANES (C.A.C.)' },
    { id: 3106, name: 'RADIO PATRULLAS 110 - ZONA SUD' },
    { id: 3107, name: 'P.A.C. - ZONA SUD' },
    { id: 3108, name: 'GACIP - ZONA SUD' },
    { id: 3109, name: 'U.P.A.R DELTA -ZONA SUD' },
    { id: 3110, name: 'COMANDO REGIONAL - ZONA SUD' },
  ],
  4: [
    { id: 4000, name: 'POLICIA RURAL' },
    { id: 4101, name: 'POLICIA RURAL Y FRONTERIZA' },
    { id: 4102, name: 'ACHACACHI' },
    { id: 4103, name: 'CARANAVI' },
    { id: 4104, name: 'VIACHA' },
    { id: 4105, name: 'IXIAMAS' },
    { id: 4106, name: 'SAN BUENA VENTURA' },
    { id: 4107, name: 'SICA SICA' },
    { id: 4108, name: 'LAHUACHACA' },
    { id: 4109, name: 'KONANI' },
    { id: 4110, name: 'PANDURO' },
    { id: 4111, name: 'COLLANA NORTE' },
    { id: 4112, name: 'UMALA' },
    { id: 4113, name: 'AYO AYO' },
    { id: 4114, name: 'COLQUENCHA' },
    { id: 4115, name: 'MARQUIRIVI' },
    { id: 4116, name: 'MACHACAMARCA' },
    { id: 4117, name: 'CALAMARCA' },
    { id: 4118, name: 'SAN ANTONIO DE SENKATA' },
    { id: 4119, name: 'VILAQUE COPATA' },
    { id: 4120, name: 'PATACAMAYA' },
    { id: 4121, name: 'CHARAZANI' },
    { id: 4122, name: 'COTA PAMPA' },
    { id: 4123, name: 'PUERTO ACOSTA' },
    { id: 4124, name: 'ESCOMA' },
    { id: 4125, name: 'MOCOMOCO' },
    { id: 4126, name: 'TAJANI' },
    { id: 4127, name: 'CARABUCO' },
    { id: 4128, name: 'CHAGUAYA' },
    { id: 4129, name: 'AMBANA' },
    { id: 4130, name: 'SAN ANTONIO CARANAVI' },
    { id: 4131, name: 'APOLO' },
    { id: 4132, name: 'PELECHUCO' },
    { id: 4133, name: 'SUCHEZ' },
    { id: 4134, name: 'ULLA ULLA' },
    { id: 4135, name: 'SAN PEDRO DE CURAHUARA' },
    { id: 4136, name: 'CHILAHUALA' },
    { id: 4137, name: 'CHACARILLA' },
    { id: 4138, name: 'PAPEL PAMPA' },
    { id: 4139, name: 'SAN FELIPE DE CHALLA' },
    { id: 4140, name: 'JESUS DE MACHACA' },
    { id: 4141, name: 'SANTO DOMINGO' },
    { id: 4142, name: 'MEJILLONES DE MACHACA' },
    { id: 4143, name: 'CALLA TUPAC KATARI' },
    { id: 4144, name: 'CORPA' },
    { id: 4145, name: 'AGUALLAMAYA' },
    { id: 4146, name: 'SAN ANDRES DE MACHACA' },
    { id: 4147, name: 'NAZACARA INGAVI' },
    { id: 4148, name: 'CENTRO MAURI' },
    { id: 4149, name: 'VILLA PUSAMA' },
    { id: 4150, name: 'SOMBRA PATA' },
    { id: 4151, name: 'CONCHACOLLO' },
    { id: 4152, name: 'LAQUINAMAYA' },
    { id: 4153, name: 'TARACO' },
    { id: 4154, name: 'SANTA ROSA DE TARACO' },
    { id: 4155, name: 'DESAGUADERO' },
    { id: 4156, name: 'TIAHUANACU' },
    { id: 4157, name: 'TIHUANACU' },
    { id: 4158, name: 'HUACULLANI' },
    { id: 4159, name: 'GUAQUI' },
    { id: 4160, name: 'INQUISIVI' },
    { id: 4161, name: 'ICHOCA' },
    { id: 4162, name: 'CAJUATA' },
    { id: 4163, name: 'VILLA BARRIENTOS' },
    { id: 4164, name: 'VILLA LIBERTAD LICOMA' },
    { id: 4165, name: 'COLQUIRI' },
    { id: 4166, name: 'QUIME' },
    { id: 4167, name: 'SANTIAGO DE MACHACA' },
    { id: 4168, name: 'COPAPUJIO VENTILLA' },
    { id: 4169, name: 'CATACORA' },
    { id: 4170, name: 'PAYRUMANI GRANDE' },
    { id: 4171, name: 'CHIPA TOLACOLLO' },
    { id: 4172, name: 'SORATA' },
    { id: 4173, name: 'MAPIRI' },
    { id: 4174, name: 'SANTA ROSA DE MAPIRI' },
    { id: 4175, name: 'TEOPONTE' },
    { id: 4176, name: 'MAYAYA' },
    { id: 4177, name: 'COMBAYA' },
    { id: 4178, name: 'TIPUANI' },
    { id: 4179, name: 'GUANAY' },
    { id: 4180, name: 'TACACOMA' },
    { id: 4181, name: 'LURIBAY' },
    { id: 4182, name: 'SAPAAHAQUI' },
    { id: 4183, name: 'CAIROMA' },
    { id: 4184, name: 'VILOCO' },
    { id: 4185, name: 'YACO' },
    { id: 4186, name: 'CAXATA' },
    { id: 4187, name: 'PUCARANI' },
    { id: 4188, name: 'CHOJASIVI' },
    { id: 4189, name: 'PALCOCO' },
    { id: 4190, name: 'AYGACHI' },
    { id: 4191, name: 'BATALLAS' },
    { id: 4192, name: 'PEÑAS' },
    { id: 4193, name: 'LAJA' },
    { id: 4194, name: 'TAMBILLO' },
    { id: 4195, name: 'PUCHUCOLLO' },
    { id: 4196, name: 'SAN JUAN ROSARIO DE MASAYA' },
    { id: 4197, name: 'PUERTO PEREZ' },
    { id: 4198, name: 'COPACABANA' },
    { id: 4199, name: 'KASANI' },
    { id: 4200, name: 'TITO YUPANQUI' },
    { id: 4201, name: 'CHUMA' },
    { id: 4202, name: 'TIMUSI' },
    { id: 4203, name: 'PALCA' },
    { id: 4204, name: 'ACHOCALLA CENTRAL' },
    { id: 4205, name: 'ASUNTA QUILLVIRI' },
    { id: 4206, name: 'DISTRITO N° 7' },
    { id: 4207, name: 'DISTRITO N° 8' },
    { id: 4208, name: 'DISTRITO N° 9' },
    { id: 4209, name: 'MECAPACA' },
    { id: 4210, name: 'HUARICANA' },
    { id: 4211, name: 'CAMSIQUI ZONGO' },
    { id: 4212, name: 'COROICO' },
    { id: 4213, name: 'CORIPATA' },
    { id: 4214, name: 'ARAPATA' },
    { id: 4215, name: 'AJLLATA GRANDE' },
    { id: 4216, name: 'ANCORAIMES' },
    { id: 4217, name: 'CHOJÑAPATA' },
    { id: 4218, name: 'CHUA COCANI' },
    { id: 4219, name: 'HUARINA' },
    { id: 4220, name: 'HUATAJATA' },
    { id: 4221, name: 'SANTIAGO DE HUATA' },
    { id: 4222, name: 'COROCORO' },
    { id: 4223, name: 'CALACOTO' },
    { id: 4224, name: 'CAQUIAVIRI' },
    { id: 4225, name: 'TINCACHI' },
    { id: 4226, name: 'ACHIRI' },
    { id: 4227, name: 'CHARAÑA' },
    { id: 4228, name: 'TRIPARTITO' },
    { id: 4229, name: 'COMANCHE' },
    { id: 4230, name: 'NAZACARA PACAJES' },
    { id: 4231, name: 'SANTIAGO DE CALLAPA' },
    { id: 4232, name: 'WALDO BALLIVIAN' },
    { id: 4233, name: 'CHULUMANI' },
    { id: 4234, name: 'IRUPANA' },
    { id: 4235, name: 'ASUNTA' },
    { id: 4236, name: 'SAN JUAN DE COTAPATA' },
    { id: 4237, name: 'PALOS BLANCOS' },
    { id: 4238, name: 'SANTA ANADE MOSETENES' },
    { id: 4239, name: 'YANACACHI' },
    { id: 4240, name: 'PUENTE VILLA' },
  ],
  5: [
    { id: 5101, name: 'DIRECCION DEPARTAMENTAL DE TRANSITO, TRANSPORTE Y SEGURIDAD VIAL' },
  ],
}

module.exports = { areas, unitsByArea }